#Operators

Operators are special symbols in Python that carry out arithmetic or logical computation.
The value that the operator operates on is called the operand

1) Arithmetic operators.

Addition.
Subtraction.
Multiplication.
Division.
Modulus.
Exponentiation.
Floor division.

2) Assignment operators.

Operator	Operand	Operation
+=	          a, b	 a+=b
-=	          a, b	 a-=b
*=	          a, b	 a*=b
/=	          a, b	 a/=b
%=            a, b	 a%=b
//=           a, b	 a//=b

3) Comparison operators.

Operator	Name	            Example
==	        Equal	            x == y
!=	        Not equal	        x != y
>	        Greater than        x > y
<	        Less than	        x < y
>=	        Greater than or equal to	x >= y
<=	        Less than or equal to	x <= y

4) Logical operators.

Operator	Description	                                    Example
and	        Returns True if both statements are true	    x < 5 and x < 10
or	        Returns True if one of the statements is true	x < 5 or x < 4
not	        Reverse the result, returns False if the result is true	   not(x < 5 and x < 10)

5) Identity operators.

Operator	Description	                     Example
is	        Returns true if both variables
            are the same object	             x is y
is not	    Returns true if both variables
            are not the same object	         x is not y

6) Membership operators.

Operator	Description	                      Example
in	        Returns True if a sequence with
            the specified value is present
            in the object	                  x in y
not in	    Returns True if a sequence with
            the specified value is not present
            in the object	                 x not in y
