#Variables -

Variable is a name which is used to refer memory location of value.
Variable also known as identifier and used to hold the value.

Write Operations and Read Operations

Rules of variable – Variable means contains which store values.
1.	A variable name must start with a letter or the underscore character.
2.	A variable name cannot start with a number.
3.	A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
4.	Variable names are case-sensitive (age, Age and AGE are three different variables).

x = 10 will go to the address of the variable
